<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:oe="http://www.ebutilities.at/datenplattform/0700" targetNamespace="http://www.ebutilities.at/datenplattform/0700" elementFormDefault="qualified">

	<xsd:include schemaLocation="CommonTypes.xsd" />

	<xsd:element name="MoveOutRequest">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="MarketParticipantData" type="oe:MarketParticipantData" />
				<xsd:element name="MessageData" type="oe:MoveOutRequestMessageData" />
				<xsd:element name="ProcessData" type="oe:MoveOutRequestProcessData" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="MoveOutRequestMessageData">
		<xsd:complexContent>
			<xsd:extension base="oe:MessageDataMin">
				<xsd:sequence>
					<xsd:element name="MessageCode">
						<xsd:simpleType>
							<xsd:restriction base="oe:MessageCode">
								<xsd:enumeration value="ANFRAGE_ABM" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="CasesData" type="oe:CasesDataSingle" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="MoveOutRequestProcessData">
		<xsd:sequence>
			<xsd:element name="ContractPartnerData" type="oe:ContractPartnerData" />
			<xsd:element name="DeliveryAddressData" type="oe:DeliveryAddressDataFull" />
			<xsd:element name="CorrespondenceAddressData" type="oe:CorrespondenceAddressData" minOccurs="0" />
			<xsd:element name="MeteringPointData">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:extension base="oe:MeteringPointDataBasic">
							<xsd:sequence>
								<xsd:element name="DeviceData" minOccurs="0" maxOccurs="1000">
									<xsd:complexType>
										<xsd:complexContent>
											<xsd:extension base="oe:DeviceDataMin">
												<xsd:sequence>
													<xsd:element name="MeterData" type="oe:MeterData" minOccurs="0" maxOccurs="1000"/>
												</xsd:sequence>
											</xsd:extension>
										</xsd:complexContent>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:extension>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ProcessControlData">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="RequestedEndSupplyData" type="oe:RequestedEndSupplyDataBasic" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="AdditionalData" type="oe:AdditionalData" minOccurs="0" maxOccurs="1000" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>
