<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ebutilities.at/datenplattform/0700" elementFormDefault="qualified">

	<xsd:include schemaLocation="CancellationMoveInConfirmation.xsd" />
	<xsd:include schemaLocation="CancellationMoveInGasGridManagerNotification.xsd" />
	<xsd:include schemaLocation="CancellationMoveInRequest.xsd" />
	<xsd:include schemaLocation="ConsumptionInfoTransmission.xsd" />
	<xsd:include schemaLocation="ContractDataRequest.xsd" />
	<xsd:include schemaLocation="ContractDataResponse.xsd" />
	<xsd:include schemaLocation="ContractlessStateConfirmation.xsd" />
	<xsd:include schemaLocation="ContractlessStateGasGridManagerConfirmation.xsd" />
	<xsd:include schemaLocation="ContractlessStateNotification.xsd" />
	<xsd:include schemaLocation="ContractlessStateRequest.xsd" />
	<xsd:include schemaLocation="ContractTerminationRequest.xsd" />
	<xsd:include schemaLocation="ContractTerminationResponse.xsd" />
	<xsd:include schemaLocation="CustomerMeteringPointRequest.xsd" />
	<xsd:include schemaLocation="CustomerMeteringPointResponse.xsd" />
	<xsd:include schemaLocation="MessageTransmission.xsd" />
	<xsd:include schemaLocation="MoveInConfirmation.xsd" />
	<xsd:include schemaLocation="MoveInEstimation.xsd" />
	<xsd:include schemaLocation="MoveInShift.xsd" />
	<xsd:include schemaLocation="MoveInGasGridManagerNotification.xsd" />
	<xsd:include schemaLocation="MoveInGasGridManagerResponse.xsd" />
	<xsd:include schemaLocation="MoveInRequest.xsd" />
	<xsd:include schemaLocation="MoveOutConfirmation.xsd" />
	<xsd:include schemaLocation="MoveOutEstimation.xsd" />
	<xsd:include schemaLocation="MoveOutShift.xsd" />
	<xsd:include schemaLocation="MoveOutGasGridManagerConfirmation.xsd" />
	<xsd:include schemaLocation="MoveOutRequest.xsd" />
	<xsd:include schemaLocation="Notification.xsd" />
	<xsd:include schemaLocation="PoaVerificationRequest.xsd" />
	<xsd:include schemaLocation="PoaVerificationResponse.xsd" />
	<xsd:include schemaLocation="PoaVerificationTransmission.xsd" />
	<xsd:include schemaLocation="PowerOfAttorneyTransmission.xsd" />
	<xsd:include schemaLocation="PremiseMeteringPointRequest.xsd" />
	<xsd:include schemaLocation="PremiseMeteringPointResponse.xsd" />
	<xsd:include schemaLocation="RevertMoveInConfirmation.xsd" />
	<xsd:include schemaLocation="RevertMoveInGasGridManagerNotification.xsd" />
	<xsd:include schemaLocation="RevertMoveInRequest.xsd" />
	<xsd:include schemaLocation="RevertMoveOutConfirmation.xsd" />
	<xsd:include schemaLocation="RevertMoveOutGasGridManagerNotification.xsd" />
	<xsd:include schemaLocation="RevertMoveOutRequest.xsd" />
	<xsd:include schemaLocation="SupplierChangeConfirmation.xsd" />
	<xsd:include schemaLocation="SupplierChangeConsumptionInfo.xsd" />
	<xsd:include schemaLocation="SupplierChangeGasGridManagerNotification.xsd" />
	<xsd:include schemaLocation="SupplierChangeGasGridManagerConfirmation.xsd" />
	<xsd:include schemaLocation="SupplierChangeInfoRecord.xsd" />
	<xsd:include schemaLocation="SupplierChangeNotification.xsd" />
	<xsd:include schemaLocation="SupplierChangeObjectionRecord.xsd" />
	<xsd:include schemaLocation="SupplierChangeRequest.xsd" />
	<xsd:include schemaLocation="SupplyRequest.xsd" />

</xsd:schema>
