<?xml version = "1.0" encoding = "UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:oe="http://www.ebutilities.at/datenplattform/0700" targetNamespace="http://www.ebutilities.at/datenplattform/0700" elementFormDefault="qualified">

	<xsd:include schemaLocation="CommonTypes.xsd" />

	<xsd:element name="MoveOutEstimation">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="MarketParticipantData" type="oe:MarketParticipantData" />
				<xsd:element name="MessageData" type="oe:MoveOutEstimationMessageData" />
				<xsd:element name="ProcessData" type="oe:MoveOutEstimationProcessData" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="MoveOutEstimationMessageData">
		<xsd:complexContent>
			<xsd:extension base="oe:MessageDataMin">
				<xsd:sequence>
					<xsd:element name="MessageCode">
						<xsd:simpleType>
							<xsd:restriction base="oe:MessageCode">
								<xsd:enumeration value="ERSTE_ABM" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="CasesData" type="oe:CasesDataSingle" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="MoveOutEstimationProcessData">
		<xsd:sequence>
			<xsd:element name="ContractPartnerData" type="oe:ContractPartnerData" />
			<xsd:element name="DeliveryAddressData" type="oe:DeliveryAddressDataFull" />
			<xsd:element name="MeteringPointData" type="oe:MeteringPointDataBasic" />
			<xsd:element name="ProcessControlData">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="RequestedEndSupplyData" type="oe:RequestedEndSupplyDataMin" />
						<xsd:element name="EstimatedEndSupplyDate" type="xsd:date" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="AdditionalData" type="oe:AdditionalData" minOccurs="0" maxOccurs="1000" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>
